import { Link, useLocation } from 'react-router-dom';

const navByRole={Person:[['Home','/home'],['Societies','/societies'],['My Society','/my-society'],['Exchange','/exchange'],['History','/history'],['Profile','/profile']],Ngo:[['Dashboard','/ngo/dashboard'],['Societies','/ngo/societies'],['Contracts','/ngo/contracts'],['Collections','/ngo/collections'],['Events','/ngo/events'],['Profile','/ngo/verification']],Bhangarwala:[['Requests','/bhangarwala/requests'],['Active Job','/bhangarwala/active-job'],['History','/bhangarwala/history'],['Profile','/bhangarwala/profile']]};
export function Navbar({variant='Person',className,children}){const {pathname}=useLocation();if(children)return <nav className={className}>{children}</nav>;return <header className="fixed top-0 left-0 right-0 z-50 border-b border-outline-variant bg-surface-container-lowest"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-space-md px-gutter"><Link to="/" className="font-headline-sm text-headline-sm text-primary">♻ ReWaste</Link><nav className="hidden items-center gap-space-sm md:flex">{navByRole[variant].map(([name,to])=><Link key={to} to={to} className={`rounded-lg px-space-md py-space-xs font-label-lg ${pathname===to?'bg-primary-container text-on-primary':'text-on-surface-variant hover:text-primary'}`}>{name}</Link>)}</nav><span className="rounded-full bg-surface-container-high px-3 py-1 text-label-sm">{variant}</span></div></header>}
export function Footer(){return <footer className="mt-auto w-full bg-surface-container-lowest py-space-lg"><div className="mx-auto flex max-w-7xl justify-between px-margin text-body-sm text-on-surface-variant"><span>© 2025 ReWaste Materials Ledger.</span><span>Operational Circular Network</span></div></footer>}
export function SocietyCard({name='Community Society',children}){return <article className="rounded-xl bg-white p-space-lg shadow-sm">{children||<h2 className="font-headline-md text-headline-md">{name}</h2>}</article>}
export function TrustScoreGauge({score=94.8}){return <div className="grid h-16 w-16 place-items-center rounded-full border-4 border-primary font-label-lg text-primary" role="meter" aria-valuenow={score} aria-valuemin="0" aria-valuemax="100">{score}%</div>}
export function StatusStepper({steps=['Created','In Transit','Verified','Dispersed'],active=0}){return <ol className="flex items-center gap-2">{steps.map((step,i)=><li key={step} className={`flex-1 border-t-2 pt-2 text-label-sm ${i<=active?'border-primary text-primary':'border-outline-variant text-outline'}`}>{step}</li>)}</ol>}
export function MapPanel({children}){return <section className="relative min-h-64 overflow-hidden rounded-xl bg-surface-container-high p-space-lg">{children}</section>}
export function StatCard({label,value,trend}){return <article className="rounded-xl bg-white p-space-lg shadow-sm"><p className="text-body-sm text-on-surface-variant">{label}</p><strong className="font-headline-lg text-headline-lg">{value}</strong>{trend&&<span className="ml-2 text-primary">{trend}</span>}</article>}
export function EventCard({title,children}){return <article className="border-l-2 border-primary py-2 pl-space-md"><h3 className="font-label-lg">{title}</h3>{children}</article>}
export function QuoteCard({children}){return <article className="rounded-xl border border-outline-variant bg-white p-space-lg shadow-sm">{children}</article>}
export function ContractRow({children}){return <tr className="transition-colors hover:bg-surface-container-low">{children}</tr>}
export function PaymentSplitModal({open=false,onClose,children}){return open?<div className="fixed inset-0 z-50 grid place-items-center bg-inverse-surface/60 p-4"><section className="w-full max-w-xl rounded-xl bg-white p-space-lg shadow-lg"><button type="button" onClick={onClose} className="float-right">Close</button>{children}</section></div>:null}
export function PhotoUploadDropzone({onFiles}){return <label className="block cursor-pointer rounded-xl border-2 border-dashed border-outline-variant bg-surface-container-low p-space-xl text-center">Drop photos here or choose files<input className="sr-only" type="file" accept="image/*" multiple onChange={e=>onFiles?.(Array.from(e.target.files||[]))}/></label>}
export function StatusBadge({status='Pending'}){return <span className="inline-flex rounded-full bg-secondary-fixed px-3 py-1 text-label-sm text-secondary">{status}</span>}
